[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly-2023-06-30"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
